GCS_PROJECT_BRANDING = taulabs
GCS_PROJECT_BRANDING_PRETTY = Tau Labs
GCS_PROJECT_BRANDING_HELP = http://github.com/TauLabs
DEFINES += 'GCS_PROJECT_BRANDING=\'\"$$GCS_PROJECT_BRANDING\"\''
DEFINES += 'GCS_PROJECT_BRANDING_PRETTY=\'\"$$GCS_PROJECT_BRANDING_PRETTY\"\''
DEFINES += 'GCS_PROJECT_BRANDING_HELP=\'\"$$GCS_PROJECT_BRANDING_HELP\"\''
