#!/usr/bin/env bash -e -v

APP="${1?}"
PLUGINS="${APP}/Contents/Plugins"

# Specify a list of all the qml directories that need imports
QMLDIR="${APP}/Contents/Resources/welcome"

# macdeployqt will copy all the Qt5 binaries to the app bundle and relink as appropriate

#pushd/popd: workaround QTBUG-46404 -- need to be next to macdeployqt's path

pushd "${QT_SDK_BIN_PATH}"

./macdeployqt "${APP}" -verbose=2 -no-strip -always-overwrite -qmldir="$QMLDIR"

popd

# Copy SDL files
echo "Copying SDL"
cp -r "/Library/Frameworks/SDL.framework" "${APP}/Contents/Frameworks/"

# these are optional
echo "Changing package identification of SDL"
install_name_tool -id \
       @executable_path/../Frameworks/SDL.framework/SDL \
       "${APP}/Contents/Frameworks/SDL.framework/SDL" || true
install_name_tool -change \
       @rpath/SDL.framework/Versions/A/SDL \
       "@executable_path/../Frameworks/SDL.framework/SDL" \
       "${APP}/Contents/Plugins/libsdlgamepad.1.dylib" || true
