#!/bin/bash

# the following environment variables must be set
: ${ROOT_DIR?} ${BUILD_DIR?} ${PACKAGE_LBL?} ${PACKAGE_DIR?} ${FW_DIR?}

# more variables
APP_PATH="${BUILD_DIR}/ground/gcs/bin/Tau Labs GCS.app"
TEMP_FILE="${PACKAGE_DIR}/TauLabs-temp.dmg"
OUT_FILE="${PACKAGE_DIR}/TauLabs-${PACKAGE_LBL}.dmg"
VOL_NAME="Tau Labs"

# prepare the stage
rm -f "${TEMP_FILE}"
rm -f "${OUT_FILE}"

hdiutil convert "${ROOT_DIR}/package/osx/TauLabs.dmg" \
	-format UDRW -o "${TEMP_FILE}"
device=$(hdiutil attach  "${TEMP_FILE}" | \
         egrep '^/dev/' | sed 1q | awk '{print $1}')

# packaging goes here
cp -r "${APP_PATH}" "/Volumes/${VOL_NAME}"
#cp -r "${FW_DIR}" "/Volumes/${VOL_NAME}/firmware"
cp "${FW_DIR}/fw_quanton-${PACKAGE_LBL}.opfw" "/Volumes/${VOL_NAME}/Firmware"
cp "${FW_DIR}/fw_freedom-${PACKAGE_LBL}.opfw" "/Volumes/${VOL_NAME}/Firmware"
cp "${FW_DIR}/fw_flyingf3-${PACKAGE_LBL}.opfw" "/Volumes/${VOL_NAME}/Firmware"
cp "${FW_DIR}/fw_flyingf4-${PACKAGE_LBL}.opfw" "/Volumes/${VOL_NAME}/Firmware"
cp "${FW_DIR}/fw_coptercontrol-${PACKAGE_LBL}.opfw" "/Volumes/${VOL_NAME}/Firmware"
cp "${FW_DIR}/fw_revomini-${PACKAGE_LBL}.opfw" "/Volumes/${VOL_NAME}/Firmware"
cp "${FW_DIR}/fw_pipxtreme-${PACKAGE_LBL}.opfw" "/Volumes/${VOL_NAME}/Firmware"
cp "${FW_DIR}/fw_revolution-${PACKAGE_LBL}.opfw" "/Volumes/${VOL_NAME}/Firmware"

cp "${BUILD_DIR}/matlab/LogConvert.m" "/Volumes/${VOL_NAME}/Utilities/LogConvert-${PACKAGE_LBL}.m"

cp "${ROOT_DIR}/HISTORY.txt" "/Volumes/${VOL_NAME}"

"${ROOT_DIR}/package/osx/libraries" \
	"/Volumes/${VOL_NAME}/Tau Labs GCS.app" || exit 1

hdiutil detach ${device}

min=`hdiutil resize ${TEMP_FILE} | awk \{print\ \$\1\}`
echo "Resizing dmg to ${min}"

hdiutil resize -sectors ${min} ${TEMP_FILE}
hdiutil convert "${TEMP_FILE}" -format UDZO -o "${OUT_FILE}"

# cleanup
rm "${TEMP_FILE}"
