var group___tau_labs_modules =
[
    [ "Actuator Module", "group___actuator_module.html", null ],
    [ "Airspeed Module", "group___airspeed_module.html", null ],
    [ "Altitude hold module", "group___altitude_hold_module.html", null ],
    [ "Copter Control Attitude Estimation", "group___attitude_module_c_c.html", null ],
    [ "Attitude and state estimation module", "group___attitude_module.html", null ],
    [ "Autotuning Module", "group___autotuning_module.html", null ],
    [ "Battery Module", "group___battery_module.html", null ],
    [ "Camera Stabilization Module", "group___camera_stab.html", null ],
    [ "Com Port to USB VCP Bridge Module", "group___com_usb_bridge_module.html", null ],
    [ "Fault Module", "group___fault_module.html", null ],
    [ "Read the firmware IAP values", "group___firmware_i_a_p_module.html", null ],
    [ "Fixed wing path follower module", "group___fixed_wing_path_follower.html", null ],
    [ "Flight Plan Module", "group___flight_plan.html", null ],
    [ "Generic I2C sensor interface", "group___generic_i2_c_sensor.html", null ],
    [ "GPS Module", "group___g_s_p_module.html", null ],
    [ "Path follower for ground based vehicles", "group___ground_path_follower.html", null ],
    [ "Control Module", "group___control.html", null ],
    [ "osdgen Module", "group___o_s_d_g_e_n_module.html", null ],
    [ "osdinput Module", "group__osdinput_module.html", null ],
    [ "WavPlayer Module", "group___wav_player_module.html", null ],
    [ "OveroSync Module", "group___overo_sync_module.html", null ],
    [ "Path Follower Module", "group___path_follower_module.html", null ],
    [ "Path Planner Module", "group___path_planner_module.html", null ],
    [ "PipXtreme Module", "group___pip_xtreme_module.html", null ],
    [ "Com Port to Radio Bridge Module", "group___radio_com_bridge_module.html", null ],
    [ "Sensor acquisition module", "group___sensors.html", null ],
    [ "Visualization module for simulation", "group___visualization_module.html", null ],
    [ "Stabilization Module", "group___stabilization_module.html", null ],
    [ "Copter Control State Estimation", "group___c_c_state.html", null ],
    [ "System Module", "group___system_module.html", null ],
    [ "Telemetry Module", "group___telemetry_module.html", null ],
    [ "TxPID Module", "group___tx_p_i_d_module.html", null ],
    [ "UAVO to Mavlink Bridge Module", "group___u_a_v_o_mavlink_bridge.html", null ],
    [ "Vibration analysis module", "group___vibration_analysis_module.html", null ],
    [ "VTOL path follower module", "group___vtol_path_follower.html", null ]
];