var group___i2_c___exported___constants =
[
    [ "I2C_mode", "group___i2_c__mode.html", null ],
    [ "I2C_duty_cycle_in_fast_mode", "group___i2_c__duty__cycle__in__fast__mode.html", null ],
    [ "I2C_acknowledgement", "group___i2_c__acknowledgement.html", null ],
    [ "I2C_transfer_direction", "group___i2_c__transfer__direction.html", null ],
    [ "I2C_acknowledged_address", "group___i2_c__acknowledged__address.html", null ],
    [ "I2C_registers", "group___i2_c__registers.html", null ],
    [ "I2C_SMBus_alert_pin_level", "group___i2_c___s_m_bus__alert__pin__level.html", null ],
    [ "I2C_PEC_position", "group___i2_c___p_e_c__position.html", null ],
    [ "I2C_interrupts_definition", "group___i2_c__interrupts__definition.html", null ],
    [ "I2C_flags_definition", "group___i2_c__flags__definition.html", null ],
    [ "I2C_Events", "group___i2_c___events.html", null ],
    [ "I2C_own_address1", "group___i2_c__own__address1.html", null ],
    [ "I2C_clock_speed", "group___i2_c__clock__speed.html", null ],
    [ "I2C_Analog_Filter", "group___i2_c___analog___filter.html", null ],
    [ "I2C_Digital_Filter", "group___i2_c___digital___filter.html", null ],
    [ "I2C_DMA_transfer_requests", "group___i2_c___d_m_a__transfer__requests.html", null ],
    [ "I2C_slave_address", "group___i2_c__slave__address.html", null ],
    [ "I2C_own_address2", "group___i2_c__own__address2.html", null ],
    [ "I2C_own_address2_mask", "group___i2_c__own__address2__mask.html", null ],
    [ "I2C_timeout", "group___i2_c__timeout.html", null ],
    [ "I2C_ReloadEndMode_definition", "group___i2_c___reload_end_mode__definition.html", null ],
    [ "I2C_StartStopMode_definition", "group___i2_c___start_stop_mode__definition.html", null ],
    [ "I2C_NACK_position", "group___i2_c___n_a_c_k__position.html", null ]
];