var group___d_m_a___exported___constants =
[
    [ "DMA_data_transfer_direction", "group___d_m_a__data__transfer__direction.html", null ],
    [ "DMA_peripheral_incremented_mode", "group___d_m_a__peripheral__incremented__mode.html", null ],
    [ "DMA_memory_incremented_mode", "group___d_m_a__memory__incremented__mode.html", null ],
    [ "DMA_peripheral_data_size", "group___d_m_a__peripheral__data__size.html", null ],
    [ "DMA_memory_data_size", "group___d_m_a__memory__data__size.html", null ],
    [ "DMA_circular_normal_mode", "group___d_m_a__circular__normal__mode.html", null ],
    [ "DMA_priority_level", "group___d_m_a__priority__level.html", null ],
    [ "DMA_memory_to_memory", "group___d_m_a__memory__to__memory.html", null ],
    [ "DMA_interrupts_definition", "group___d_m_a__interrupts__definition.html", null ],
    [ "DMA_flags_definition", "group___d_m_a__flags__definition.html", null ],
    [ "DMA_Buffer_Size", "group___d_m_a___buffer___size.html", null ],
    [ "DMA_channel", "group___d_m_a__channel.html", null ],
    [ "DMA_data_buffer_size", "group___d_m_a__data__buffer__size.html", null ],
    [ "DMA_fifo_direct_mode", "group___d_m_a__fifo__direct__mode.html", null ],
    [ "DMA_fifo_threshold_level", "group___d_m_a__fifo__threshold__level.html", null ],
    [ "DMA_memory_burst", "group___d_m_a__memory__burst.html", null ],
    [ "DMA_peripheral_burst", "group___d_m_a__peripheral__burst.html", null ],
    [ "DMA_fifo_status_level", "group___d_m_a__fifo__status__level.html", null ],
    [ "DMA_interrupt_enable_definitions", "group___d_m_a__interrupt__enable__definitions.html", null ],
    [ "DMA_interrupts_definitions", "group___d_m_a__interrupts__definitions.html", null ],
    [ "DMA_peripheral_increment_offset", "group___d_m_a__peripheral__increment__offset.html", null ],
    [ "DMA_flow_controller_definitions", "group___d_m_a__flow__controller__definitions.html", null ],
    [ "DMA_memory_targets_definitions", "group___d_m_a__memory__targets__definitions.html", null ]
];