var group___open_pilot_modules =
[
    [ "State Module", "group___state.html", "group___state" ],
    [ "Estimation", "group___attitude.html", "group___attitude" ],
    [ "Actuator Module", "group___actuator_module.html", "group___actuator_module" ],
    [ "Airspeed Module", "group___airspeed_module.html", "group___airspeed_module" ],
    [ "module", "group___autotuning.html", "group___autotuning" ],
    [ "Battery Module", "group___battery_module.html", "group___battery_module" ],
    [ "Camera Stabilization Module", "group___camera_stab.html", "group___camera_stab" ],
    [ "Com Port to USB VCP Bridge Module", "group___com_usb_bridge_module.html", "group___com_usb_bridge_module" ],
    [ "Altitude Module", "group___altitude_module.html", "group___altitude_module" ],
    [ "Fault Module", "group___fault_module.html", "group___fault_module" ],
    [ "Flight Plan Module", "group___flight_plan.html", "group___flight_plan" ],
    [ "GPS Module", "group___g_s_p_module.html", "group___g_s_p_module" ],
    [ "Path follower for ground based vehicles", "group___ground_path_follower.html", "group___ground_path_follower" ],
    [ "MK Serial Control Module", "group___m_k_serial_module.html", "group___m_k_serial_module" ],
    [ "OSD Module", "group___o_s_d_module.html", "group___o_s_d_module" ],
    [ "osdgen Module", "group___o_s_d_g_e_n_module.html", "group___o_s_d_g_e_n_module" ],
    [ "osdinput Module", "group__osdinput_module.html", "group__osdinput_module" ],
    [ "WavPlayer Module", "group___wav_player_module.html", "group___wav_player_module" ],
    [ "Telemetry Module", "group___telemetry_module.html", "group___telemetry_module" ],
    [ "Module", "group___path_follower.html", "group___path_follower" ],
    [ "Path Planner Module", "group___path_planner.html", "group___path_planner" ],
    [ "PipXtreme Module", "group___pip_xtreme_module.html", "group___pip_xtreme_module" ],
    [ "Com Port to Radio Bridge Module", "group___radio_com_bridge_module.html", "group___radio_com_bridge_module" ],
    [ "Sensors", "group___sensors.html", "group___sensors" ],
    [ "Visualization", "group___visualization.html", "group___visualization" ],
    [ "Stabilization Module", "group___stabilization_module.html", "group___stabilization_module" ],
    [ "System Module", "group___system_module.html", "group___system_module" ],
    [ "TxPID Module", "group___tx_p_i_d_module.html", "group___tx_p_i_d_module" ],
    [ "Path follower for VTOL aircrafts", "group___vtol_path_follower.html", "group___vtol_path_follower" ]
];