var modules =
[
    [ "Basic Math Functions", "group__group_math.html", "group__group_math" ],
    [ "Fast Math Functions", "group__group_fast_math.html", "group__group_fast_math" ],
    [ "Complex Math Functions", "group__group_cmplx_math.html", "group__group_cmplx_math" ],
    [ "Filtering Functions", "group__group_filters.html", "group__group_filters" ],
    [ "Matrix Functions", "group__group_matrix.html", "group__group_matrix" ],
    [ "Transform Functions", "group__group_transforms.html", "group__group_transforms" ],
    [ "Controller Functions", "group__group_controller.html", "group__group_controller" ],
    [ "Statistics Functions", "group__group_stats.html", "group__group_stats" ],
    [ "Support Functions", "group__group_support.html", "group__group_support" ],
    [ "Interpolation Functions", "group__group_interpolation.html", "group__group_interpolation" ],
    [ "Examples", "group__group_examples.html", null ],
    [ "CMSIS Global Defines", "group___c_m_s_i_s__glob__defs.html", null ],
    [ "Defines and Type Definitions", "group___c_m_s_i_s__core__register.html", "group___c_m_s_i_s__core__register" ],
    [ "Functions and Instructions Reference", "group___c_m_s_i_s___core___function_interface.html", "group___c_m_s_i_s___core___function_interface" ],
    [ "CMSIS Core Instruction Interface", "group___c_m_s_i_s___core___instruction_interface.html", "group___c_m_s_i_s___core___instruction_interface" ],
    [ "xCoRoutineCreate", "group__x_co_routine_create.html", null ],
    [ "vCoRoutineSchedule", "group__v_co_routine_schedule.html", null ],
    [ "crSTART", "group__cr_s_t_a_r_t.html", null ],
    [ "crDELAY", "group__cr_d_e_l_a_y.html", null ],
    [ "crQUEUE_SEND", "group__cr_q_u_e_u_e___s_e_n_d.html", null ],
    [ "crQUEUE_RECEIVE", "group__cr_q_u_e_u_e___r_e_c_e_i_v_e.html", null ],
    [ "crQUEUE_SEND_FROM_ISR", "group__cr_q_u_e_u_e___s_e_n_d___f_r_o_m___i_s_r.html", null ],
    [ "crQUEUE_RECEIVE_FROM_ISR", "group__cr_q_u_e_u_e___r_e_c_e_i_v_e___f_r_o_m___i_s_r.html", null ],
    [ "xQueueCreate", "group__x_queue_create.html", null ],
    [ "xQueueSend", "group__x_queue_send.html", null ],
    [ "xQueueReceive", "group__x_queue_receive.html", null ],
    [ "xQueueSendFromISR", "group__x_queue_send_from_i_s_r.html", null ],
    [ "xQueueReceiveFromISR", "group__x_queue_receive_from_i_s_r.html", null ],
    [ "vSemaphoreCreateBinary", "group__v_semaphore_create_binary.html", null ],
    [ "xSemaphoreTake", "group__x_semaphore_take.html", null ],
    [ "xSemaphoreTakeRecursive", "group__x_semaphore_take_recursive.html", null ],
    [ "xSemaphoreGive", "group__x_semaphore_give.html", null ],
    [ "xSemaphoreGiveRecursive", "group__x_semaphore_give_recursive.html", null ],
    [ "xSemaphoreGiveFromISR", "group__x_semaphore_give_from_i_s_r.html", null ],
    [ "vSemaphoreCreateMutex", "group__v_semaphore_create_mutex.html", null ],
    [ "xSemaphoreCreateCounting", "group__x_semaphore_create_counting.html", null ],
    [ "xTaskCreate", "group__x_task_create.html", null ],
    [ "xTaskCreateRestricted", "group__x_task_create_restricted.html", null ],
    [ "vTaskDelete", "group__v_task_delete.html", null ],
    [ "vTaskDelay", "group__v_task_delay.html", null ],
    [ "vTaskDelayUntil", "group__v_task_delay_until.html", null ],
    [ "uxTaskPriorityGet", "group__ux_task_priority_get.html", null ],
    [ "vTaskPrioritySet", "group__v_task_priority_set.html", null ],
    [ "vTaskSuspend", "group__v_task_suspend.html", null ],
    [ "vTaskResume", "group__v_task_resume.html", null ],
    [ "vTaskResumeFromISR", "group__v_task_resume_from_i_s_r.html", null ],
    [ "vTaskStartScheduler", "group__v_task_start_scheduler.html", null ],
    [ "vTaskEndScheduler", "group__v_task_end_scheduler.html", null ],
    [ "vTaskSuspendAll", "group__v_task_suspend_all.html", null ],
    [ "xTaskResumeAll", "group__x_task_resume_all.html", null ],
    [ "PIOS Core hardware abstraction layer", "group___p_i_o_s.html", "group___p_i_o_s" ],
    [ "MSD Functions", "group___m_s_d.html", "group___m_s_d" ],
    [ "ADC_Exported_Constants", "group___a_d_c___exported___constants.html", "group___a_d_c___exported___constants" ],
    [ "ADC_Exported_Macros", "group___a_d_c___exported___macros.html", null ],
    [ "ADC_Exported_Functions", "group___a_d_c___exported___functions.html", "group___a_d_c___exported___functions" ],
    [ "CAN_Exported_Constants", "group___c_a_n___exported___constants.html", "group___c_a_n___exported___constants" ],
    [ "CAN_Exported_Macros", "group___c_a_n___exported___macros.html", null ],
    [ "CAN_Exported_Functions", "group___c_a_n___exported___functions.html", null ],
    [ "CEC_Exported_Constants", "group___c_e_c___exported___constants.html", "group___c_e_c___exported___constants" ],
    [ "CEC_Exported_Macros", "group___c_e_c___exported___macros.html", null ],
    [ "CEC_Exported_Functions", "group___c_e_c___exported___functions.html", "group___c_e_c___exported___functions" ],
    [ "DAC_Exported_Constants", "group___d_a_c___exported___constants.html", "group___d_a_c___exported___constants" ],
    [ "DAC_Exported_Macros", "group___d_a_c___exported___macros.html", null ],
    [ "DAC_Exported_Functions", "group___d_a_c___exported___functions.html", null ],
    [ "DMA_Exported_Constants", "group___d_m_a___exported___constants.html", "group___d_m_a___exported___constants" ],
    [ "DMA_Exported_Macros", "group___d_m_a___exported___macros.html", null ],
    [ "DMA_Exported_Functions", "group___d_m_a___exported___functions.html", "group___d_m_a___exported___functions" ],
    [ "EXTI_Exported_Constants", "group___e_x_t_i___exported___constants.html", "group___e_x_t_i___exported___constants" ],
    [ "EXTI_Exported_Macros", "group___e_x_t_i___exported___macros.html", null ],
    [ "EXTI_Exported_Functions", "group___e_x_t_i___exported___functions.html", "group___e_x_t_i___exported___functions" ],
    [ "FLASH_Exported_Constants", "group___f_l_a_s_h___exported___constants.html", "group___f_l_a_s_h___exported___constants" ],
    [ "FLASH_Exported_Macros", "group___f_l_a_s_h___exported___macros.html", null ],
    [ "FLASH_Exported_Functions", "group___f_l_a_s_h___exported___functions.html", "group___f_l_a_s_h___exported___functions" ],
    [ "FSMC_Exported_Constants", "group___f_s_m_c___exported___constants.html", "group___f_s_m_c___exported___constants" ],
    [ "FSMC_Exported_Macros", "group___f_s_m_c___exported___macros.html", null ],
    [ "FSMC_Exported_Functions", "group___f_s_m_c___exported___functions.html", "group___f_s_m_c___exported___functions" ],
    [ "GPIO_Exported_Constants", "group___g_p_i_o___exported___constants.html", "group___g_p_i_o___exported___constants" ],
    [ "GPIO_Exported_Macros", "group___g_p_i_o___exported___macros.html", null ],
    [ "GPIO_Exported_Functions", "group___g_p_i_o___exported___functions.html", "group___g_p_i_o___exported___functions" ],
    [ "I2C_Exported_Constants", "group___i2_c___exported___constants.html", "group___i2_c___exported___constants" ],
    [ "I2C_Exported_Macros", "group___i2_c___exported___macros.html", null ],
    [ "I2C_Exported_Functions", "group___i2_c___exported___functions.html", "group___i2_c___exported___functions" ],
    [ "RCC_Exported_Constants", "group___r_c_c___exported___constants.html", "group___r_c_c___exported___constants" ],
    [ "RCC_Exported_Macros", "group___r_c_c___exported___macros.html", null ],
    [ "RCC_Exported_Functions", "group___r_c_c___exported___functions.html", "group___r_c_c___exported___functions" ],
    [ "SDIO_Exported_Constants", "group___s_d_i_o___exported___constants.html", "group___s_d_i_o___exported___constants" ],
    [ "SDIO_Exported_Macros", "group___s_d_i_o___exported___macros.html", null ],
    [ "SDIO_Exported_Functions", "group___s_d_i_o___exported___functions.html", "group___s_d_i_o___exported___functions" ],
    [ "SPI_Exported_Constants", "group___s_p_i___exported___constants.html", "group___s_p_i___exported___constants" ],
    [ "SPI_Exported_Macros", "group___s_p_i___exported___macros.html", null ],
    [ "SPI_Exported_Functions", "group___s_p_i___exported___functions.html", "group___s_p_i___exported___functions" ],
    [ "TIM_Exported_constants", "group___t_i_m___exported__constants.html", "group___t_i_m___exported__constants" ],
    [ "TIM_Output_Compare_state", "group___t_i_m___output___compare__state.html", null ],
    [ "TIM_Output_Compare_N_state", "group___t_i_m___output___compare___n__state.html", null ],
    [ "TIM_Capture_Compare_state", "group___t_i_m___capture___compare__state.html", null ],
    [ "TIM_Capture_Compare_N_state", "group___t_i_m___capture___compare___n__state.html", null ],
    [ "Break_Input_enable_disable", "group___break___input__enable__disable.html", null ],
    [ "Break_Polarity", "group___break___polarity.html", null ],
    [ "Lock_level", "group___lock__level.html", null ],
    [ "OSSI_Off_State_Selection_for_Idle_mode_state", "group___o_s_s_i___off___state___selection__for___idle__mode__state.html", null ],
    [ "OSSR_Off_State_Selection_for_Run_mode_state", "group___o_s_s_r___off___state___selection__for___run__mode__state.html", null ],
    [ "TIM_Ouput_Compare_Preload_State", "group___t_i_m___ouput___compare___preload___state.html", null ],
    [ "TIM_Ouput_Compare_Fast_State", "group___t_i_m___ouput___compare___fast___state.html", null ],
    [ "TIM_Ouput_Compare_Clear_State", "group___t_i_m___ouput___compare___clear___state.html", null ],
    [ "TIM_Exported_Macros", "group___t_i_m___exported___macros.html", null ],
    [ "TIM_Exported_Functions", "group___t_i_m___exported___functions.html", "group___t_i_m___exported___functions" ],
    [ "USART_Exported_Constants", "group___u_s_a_r_t___exported___constants.html", "group___u_s_a_r_t___exported___constants" ],
    [ "USART_Exported_Macros", "group___u_s_a_r_t___exported___macros.html", null ],
    [ "USART_Exported_Functions", "group___u_s_a_r_t___exported___functions.html", "group___u_s_a_r_t___exported___functions" ],
    [ "COMP_Exported_Constants", "group___c_o_m_p___exported___constants.html", "group___c_o_m_p___exported___constants" ],
    [ "Output_type_enumeration", "group___output__type__enumeration.html", "group___output__type__enumeration" ],
    [ "Output_Maximum_frequency_enumeration", "group___output___maximum__frequency__enumeration.html", "group___output___maximum__frequency__enumeration" ],
    [ "Configuration_Pull-Up_Pull-Down_enumeration", "group___configuration___pull-_up___pull-_down__enumeration.html", "group___configuration___pull-_up___pull-_down__enumeration" ],
    [ "Bit_SET_and_Bit_RESET_enumeration", "group___bit___s_e_t__and___bit___r_e_s_e_t__enumeration.html", "group___bit___s_e_t__and___bit___r_e_s_e_t__enumeration" ],
    [ "OPAMP_Exported_Constants", "group___o_p_a_m_p___exported___constants.html", "group___o_p_a_m_p___exported___constants" ],
    [ "OPAMP_TrimValue", "group___o_p_a_m_p___trim_value.html", null ],
    [ "OPAMP_OutputLevel", "group___o_p_a_m_p___output_level.html", null ],
    [ "RTC_Exported_Constants", "group___r_t_c___exported___constants.html", "group___r_t_c___exported___constants" ],
    [ "CRYP_Exported_Constants", "group___c_r_y_p___exported___constants.html", "group___c_r_y_p___exported___constants" ],
    [ "DCMI_Exported_Constants", "group___d_c_m_i___exported___constants.html", "group___d_c_m_i___exported___constants" ],
    [ "HASH_Exported_Constants", "group___h_a_s_h___exported___constants.html", "group___h_a_s_h___exported___constants" ],
    [ "Interrupts and flags management functions", "group___d_m_a___group4.html", "group___d_m_a___group4" ],
    [ "Low Power modes configuration functions", "group___p_w_r___group6.html", "group___p_w_r___group6" ],
    [ "Flags management functions", "group___p_w_r___group7.html", "group___p_w_r___group7" ],
    [ "UDP Functions", "group___p_i_o_s___u_d_p.html", "group___p_i_o_s___u_d_p" ],
    [ "OpenPilot System", "group___open_pilot_system.html", "group___open_pilot_system" ],
    [ "AHRS", "group___a_h_r_s.html", "group___a_h_r_s" ],
    [ "CopterControl BootLoader", "group___copter_control_b_l.html", "group___copter_control_b_l" ],
    [ "Math", "group___math.html", "group___math" ],
    [ "Math Utilities", "group___tau_labs_math.html", "group___tau_labs_math" ],
    [ "Math Utilities", "group___open_pilot.html", "group___open_pilot" ],
    [ "Tau Labs System", "group___tau_labs_system.html", "group___tau_labs_system" ],
    [ "OpenPilot Modules", "group___open_pilot_modules.html", "group___open_pilot_modules" ],
    [ "Tau Labs Modules", "group___modules.html", "group___modules" ],
    [ "Control Module", "group___control_module.html", "group___control_module" ],
    [ "Tau Labs Modules", "group___tau_labs_modules.html", "group___tau_labs_modules" ],
    [ "GPS Module", "group___g_p_s_module.html", "group___g_p_s_module" ],
    [ "CMSIS CM3 Core Lint Configuration", "group___c_m_s_i_s___c_m3__core___lint_cinfiguration.html", null ],
    [ "CM3 Core Definitions", "group___c_m_s_i_s___c_m3__core__definitions.html", "group___c_m_s_i_s___c_m3__core__definitions" ],
    [ "CMSIS", "group___c_m_s_i_s.html", "group___c_m_s_i_s" ],
    [ "STM32F10x_StdPeriph_Driver", "group___s_t_m32_f10x___std_periph___driver.html", "group___s_t_m32_f10x___std_periph___driver" ],
    [ "STM32F30x_StdPeriph_Driver", "group___s_t_m32_f30x___std_periph___driver.html", "group___s_t_m32_f30x___std_periph___driver" ],
    [ "STM32F2xx_StdPeriph_Driver", "group___s_t_m32_f2xx___std_periph___driver.html", "group___s_t_m32_f2xx___std_periph___driver" ],
    [ "STM32_USB_OTG_DEVICE_LIBRARY", "group___s_t_m32___u_s_b___o_t_g___d_e_v_i_c_e___l_i_b_r_a_r_y.html", "group___s_t_m32___u_s_b___o_t_g___d_e_v_i_c_e___l_i_b_r_a_r_y" ],
    [ "USBD_USER", "group___u_s_b_d___u_s_e_r.html", "group___u_s_b_d___u_s_e_r" ],
    [ "USB_OTG_DRIVER", "group___u_s_b___o_t_g___d_r_i_v_e_r.html", "group___u_s_b___o_t_g___d_r_i_v_e_r" ],
    [ "STM32F4xx_StdPeriph_Driver", "group___s_t_m32_f4xx___std_periph___driver.html", "group___s_t_m32_f4xx___std_periph___driver" ],
    [ "OpenPilot BootLoader", "group___open_pilot_b_l.html", "group___open_pilot_b_l" ],
    [ "DiscoveryF4 BootLoader", "group___discovery_f4_b_l.html", null ],
    [ "Revolution BootLoader", "group___revolution_b_l.html", "group___revolution_b_l" ],
    [ "Freedom configuration files", "group___freedom.html", null ],
    [ "OpenPilot UAVObjects", "group___u_a_v_objects.html", "group___u_a_v_objects" ],
    [ "UnitTests", "group___unit_tests.html", "group___unit_tests" ]
];