var namespaces =
[
    [ "__bi", "namespace____bi.html", null ],
    [ "avr", "namespaceavr.html", null ],
    [ "bcode", "namespacebcode.html", null ],
    [ "dict", "namespacedict.html", null ],
    [ "dismantle", "namespacedismantle.html", null ],
    [ "func", "namespacefunc.html", null ],
    [ "ipm", "namespaceipm.html", null ],
    [ "ipm_host", "namespaceipm__host.html", null ],
    [ "ipm_target", "namespaceipm__target.html", null ],
    [ "list", "namespacelist.html", null ],
    [ "main", "namespacemain.html", null ],
    [ "mavlink", "namespacemavlink.html", null ],
    [ "openpilot", "namespaceopenpilot.html", null ],
    [ "pmDist", "namespacepm_dist.html", null ],
    [ "pmfeatures", "namespacepmfeatures.html", null ],
    [ "pmGenPmFeatures", "namespacepm_gen_pm_features.html", null ],
    [ "pmHeapDump", "namespacepm_heap_dump.html", null ],
    [ "pmImgCreator", "namespacepm_img_creator.html", null ],
    [ "pmOdDecoder", "namespacepm_od_decoder.html", null ],
    [ "pmOldDecoder", "namespacepm_old_decoder.html", null ],
    [ "pmReplaceCopyright", "namespacepm_replace_copyright.html", null ],
    [ "pycscope", "namespacepycscope.html", null ],
    [ "sizeof", "namespacesizeof.html", null ],
    [ "string", "namespacestring.html", null ],
    [ "sys", "namespacesys.html", null ],
    [ "test", "namespacetest.html", null ],
    [ "uavobject", "namespaceuavobject.html", null ]
];