/**
 ******************************************************************************
 * @addtogroup TauLabsModules Tau Labs Modules
 * @{
 * @addtogroup Control Control Module
 * @{
 *
 * @file       transmitter_control.h
 * @author     Tau Labs, http://taulabs.org, Copyright (C) 2013
 * @brief      Process transmitter inputs and use as control source
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef TRANSMITTER_CONTROL_H
#define TRANSMITTER_CONTROL_H

#include "stdint.h"
#include "controlcommand.h"

/*
 * These are assumptions we make in the flight code about the order of settings and their consistency between
 * objects.  Please keep this synchronized to the UAVObjects
 */
#define assumptions1 ( \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION1SETTINGS_NONE      == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_NONE)       && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION1SETTINGS_RATE      == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_RATE)       && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION1SETTINGS_AXISLOCK  == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_AXISLOCK)       && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION1SETTINGS_WEAKLEVELING      == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_WEAKLEVELING)       && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION1SETTINGS_ATTITUDEPLUS  == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_ATTITUDEPLUS)   && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION1SETTINGS_ATTITUDE  == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_ATTITUDE)      \
)

#define assumptions3 ( \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION2SETTINGS_NONE      == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_NONE)      && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION2SETTINGS_RATE      == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_RATE)      && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION2SETTINGS_AXISLOCK  == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_AXISLOCK)       && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION2SETTINGS_WEAKLEVELING      == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_WEAKLEVELING)       && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION2SETTINGS_ATTITUDEPLUS  == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_ATTITUDEPLUS)  && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION2SETTINGS_ATTITUDE  == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_ATTITUDE)     \
)

#define assumptions5 ( \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION3SETTINGS_NONE      == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_NONE)      && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION3SETTINGS_RATE      == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_RATE)      && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION3SETTINGS_AXISLOCK  == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_AXISLOCK)       && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION3SETTINGS_WEAKLEVELING      == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_WEAKLEVELING)       && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION3SETTINGS_ATTITUDEPLUS  == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_ATTITUDEPLUS)  && \
((int)CONTROLCOMMANDSETTINGS_STABILIZATION3SETTINGS_ATTITUDE  == (int)STABILIZATIONDESIRED_STABILIZATIONMODE_ATTITUDE)     \
)

#define ARMING_CHANNEL_ROLL     0
#define ARMING_CHANNEL_PITCH    1
#define ARMING_CHANNEL_YAW      2

#define assumptions7 ( \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT           -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)/2 	== ARMING_CHANNEL_ROLL) 	&& \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_ROLLRIGHT          -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)/2 	== ARMING_CHANNEL_ROLL) 	&& \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_PITCHFORWARD       -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)/2 	== ARMING_CHANNEL_PITCH) 	&& \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_PITCHAFT           -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)/2 	== ARMING_CHANNEL_PITCH) 	&& \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_YAWLEFT            -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)/2 	== ARMING_CHANNEL_YAW) 		&& \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_YAWRIGHT           -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)/2 	== ARMING_CHANNEL_YAW)		\
)

#define assumptions8 ( \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT           -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)%2 	== 0) 	&& \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_ROLLRIGHT          -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)%2 	!= 0) 	&& \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_PITCHFORWARD       -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)%2 	== 0) 	&& \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_PITCHAFT           -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)%2 	!= 0) 	&& \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_YAWLEFT            -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)%2 	== 0)	&& \
( ((int)CONTROLCOMMANDSETTINGS_ARMING_YAWRIGHT           -(int)CONTROLCOMMANDSETTINGS_ARMING_ROLLLEFT)%2 	!= 0)	\
)

#define assumptions_flightmode ( \
( (int)CONTROLCOMMANDSETTINGS_FLIGHTMODEPOSITION_MANUAL == (int) FLIGHTSTATUS_FLIGHTMODE_MANUAL) && \
( (int)CONTROLCOMMANDSETTINGS_FLIGHTMODEPOSITION_STABILIZED1 == (int) FLIGHTSTATUS_FLIGHTMODE_STABILIZED1) && \
( (int)CONTROLCOMMANDSETTINGS_FLIGHTMODEPOSITION_STABILIZED2 == (int) FLIGHTSTATUS_FLIGHTMODE_STABILIZED2) && \
( (int)CONTROLCOMMANDSETTINGS_FLIGHTMODEPOSITION_STABILIZED3 == (int) FLIGHTSTATUS_FLIGHTMODE_STABILIZED3) && \
( (int)CONTROLCOMMANDSETTINGS_FLIGHTMODEPOSITION_VELOCITYCONTROL == (int) FLIGHTSTATUS_FLIGHTMODE_VELOCITYCONTROL) && \
( (int)CONTROLCOMMANDSETTINGS_FLIGHTMODEPOSITION_POSITIONHOLD == (int) FLIGHTSTATUS_FLIGHTMODE_POSITIONHOLD) && \
( (int)CONTROLCOMMANDSETTINGS_FLIGHTMODEPOSITION_RETURNTOHOME == (int) FLIGHTSTATUS_FLIGHTMODE_RETURNTOHOME) \
)

#define assumptions_channelcount ( \
( (int)RCTRANSMITTERINPUT_CHANNEL_NUMELEM == (int)RCTRANSMITTERSETTINGS_CHANNELGROUPS_NUMELEM ) && \
( (int)RCTRANSMITTERINPUT_CHANNEL_NUMELEM == (int)RCTRANSMITTERSETTINGS_CHANNELNUMBER_NUMELEM ) && \
( (int)RCTRANSMITTERINPUT_CHANNEL_NUMELEM == (int)RCTRANSMITTERSETTINGS_CHANNELMIN_NUMELEM ) && \
( (int)RCTRANSMITTERINPUT_CHANNEL_NUMELEM == (int)RCTRANSMITTERSETTINGS_CHANNELMAX_NUMELEM ) && \
( (int)RCTRANSMITTERINPUT_CHANNEL_NUMELEM == (int)RCTRANSMITTERSETTINGS_CHANNELNEUTRAL_NUMELEM ) )

//! Initialize the transmitter control mode
int32_t transmitter_control_initialize();

//! Process inputs and arming
int32_t transmitter_control_update();

//! Select and use transmitter control
int32_t transmitter_control_select(bool reset_controller);

//! Query what the flight mode _would_ be if this is selected
uint8_t transmitter_control_get_flight_mode();

//! Get any control events
enum control_events transmitter_control_get_events();

#endif /* TRANSMITTER_CONTROL_H */

/**
 * @}
 * @}
 */
