include(../../plugins/uavobjects/uavobjects.pri)
include(../../plugins/coreplugin/coreplugin.pri)
include(../../libs/utils/utils.pri)
include(../../libs/githubreleaseapi/githubreleaseapi.pri)
include(../../libs/quazip/quazip.pri)
