include(../../plugins/coreplugin/coreplugin.pri)
include(../../plugins/uavobjects/uavobjects.pri)
include(../../plugins/uavtalk/uavtalk.pri)
include(../../plugins/uavobjectutil/uavobjectutil.pri)
include(../../libs/glc_lib/glc_lib.pri)
