Document: abovegroundlabs
Title: Debian abovegroundlabs Manual
Author: <insert document author here>
Abstract: This manual describes what abovegroundlabs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/abovegroundlabs/abovegroundlabs.sgml.gz

Format: postscript
Files: /usr/share/doc/abovegroundlabs/abovegroundlabs.ps.gz

Format: text
Files: /usr/share/doc/abovegroundlabs/abovegroundlabs.text.gz

Format: HTML
Index: /usr/share/doc/abovegroundlabs/html/index.html
Files: /usr/share/doc/abovegroundlabs/html/*.html
