.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TAULABS-GCS 1
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
taulabsgcs \- The Ground Control Station Software from the Tau Labs project
.SH SYNOPSIS
.B taulabsgcs
.RI [ options ] " file" ...
.SH DESCRIPTION
This manual page documents briefly the
.B taulabsgcs
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBtaulabsgcs\fP is a program that allows you to change settings on compatible flight controllers,
create flightpaths, view controller data, create and upload picoC scripts, replay logged data, etc...
.SH OPTIONS
.TP
.B \-help
Show summary of options.
.TP
.B \-version
Show version of program.
.TP
.B \-client
Attempt to connect to already running instance.
.TP
.B \-clean-config
Delete all existing configuration settings.
.TP
.B \-exit-after-config
Exit GCS after manipulating configuration settings.
.TP
.B \-D key=value
Override configuration settings e.g.: -D General/OverrideLanguage=de.
.TP
.B \-configfile=value
Default configuration file to load if settings file is empty.
.TP
.B \-noload <plugin>
Do not load <plugin>.
.SH AUTHOR
taulabsgcs was written by taulabs.org.
.PP
This manual page was written by taulabs.org <board@omniloco.org>.
