Document: taulabs
Title: Debian taulabs Manual
Author: <insert document author here>
Abstract: This manual describes what taulabs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/taulabs/taulabs.sgml.gz

Format: postscript
Files: /usr/share/doc/taulabs/taulabs.ps.gz

Format: text
Files: /usr/share/doc/taulabs/taulabs.text.gz

Format: HTML
Index: /usr/share/doc/taulabs/html/index.html
Files: /usr/share/doc/taulabs/html/*.html
