var searchData=
[
  ['camera_20stabilization_20module',['Camera Stabilization Module',['../group___camera_stab.html',1,'']]],
  ['can',['CAN',['../group___c_a_n.html',1,'']]],
  ['can_5fclock_5fprescaler',['CAN_clock_prescaler',['../group___c_a_n__clock__prescaler.html',1,'']]],
  ['can_5ferror_5fcode_5fconstants',['CAN_Error_Code_constants',['../group___c_a_n___error___code__constants.html',1,'']]],
  ['can_5fexported_5fconstants',['CAN_Exported_Constants',['../group___c_a_n___exported___constants.html',1,'']]],
  ['can_5fexported_5ffunctions',['CAN_Exported_Functions',['../group___c_a_n___exported___functions.html',1,'']]],
  ['can_5fexported_5fmacros',['CAN_Exported_Macros',['../group___c_a_n___exported___macros.html',1,'']]],
  ['can_5ffilter_5ffifo',['CAN_filter_FIFO',['../group___c_a_n__filter___f_i_f_o.html',1,'']]],
  ['can_5ffilter_5fmode',['CAN_filter_mode',['../group___c_a_n__filter__mode.html',1,'']]],
  ['can_5ffilter_5fnumber',['CAN_filter_number',['../group___c_a_n__filter__number.html',1,'']]],
  ['can_5ffilter_5fscale',['CAN_filter_scale',['../group___c_a_n__filter__scale.html',1,'']]],
  ['can_5fflags',['CAN_flags',['../group___c_a_n__flags.html',1,'']]],
  ['can_20frames_20transmission_20functions',['CAN Frames Transmission functions',['../group___c_a_n___group2.html',1,'']]],
  ['can_20frames_20reception_20functions',['CAN Frames Reception functions',['../group___c_a_n___group3.html',1,'']]],
  ['can_20operation_20modes_20functions',['CAN Operation modes functions',['../group___c_a_n___group4.html',1,'']]],
  ['can_20bus_20error_20management_20functions',['CAN Bus Error management functions',['../group___c_a_n___group5.html',1,'']]],
  ['can_5fidentifier_5ftype',['CAN_identifier_type',['../group___c_a_n__identifier__type.html',1,'']]],
  ['can_5finitstatus',['CAN_InitStatus',['../group___c_a_n___init_status.html',1,'']]],
  ['can_5finterrupts',['CAN_interrupts',['../group___c_a_n__interrupts.html',1,'']]],
  ['can_5foperating_5fmode',['CAN_operating_mode',['../group___c_a_n__operating__mode.html',1,'']]],
  ['can_5foperating_5fmode_5fstatus',['CAN_operating_mode_status',['../group___c_a_n__operating__mode__status.html',1,'']]],
  ['can_5fprivate_5fdefines',['CAN_Private_Defines',['../group___c_a_n___private___defines.html',1,'']]],
  ['can_5fprivate_5ffunctionprototypes',['CAN_Private_FunctionPrototypes',['../group___c_a_n___private___function_prototypes.html',1,'']]],
  ['can_5fprivate_5ffunctions',['CAN_Private_Functions',['../group___c_a_n___private___functions.html',1,'']]],
  ['can_5fprivate_5fmacros',['CAN_Private_Macros',['../group___c_a_n___private___macros.html',1,'']]],
  ['can_5fprivate_5ftypesdefinitions',['CAN_Private_TypesDefinitions',['../group___c_a_n___private___types_definitions.html',1,'']]],
  ['can_5fprivate_5fvariables',['CAN_Private_Variables',['../group___c_a_n___private___variables.html',1,'']]],
  ['can_5freceive_5ffifo_5fnumber_5fconstants',['CAN_receive_FIFO_number_constants',['../group___c_a_n__receive___f_i_f_o__number__constants.html',1,'']]],
  ['can_5fremote_5ftransmission_5frequest',['CAN_remote_transmission_request',['../group___c_a_n__remote__transmission__request.html',1,'']]],
  ['can_5fsleep_5fconstants',['CAN_sleep_constants',['../group___c_a_n__sleep__constants.html',1,'']]],
  ['can_5fstart_5fbank_5ffilter_5ffor_5fslave_5fcan',['CAN_Start_bank_filter_for_slave_CAN',['../group___c_a_n___start__bank__filter__for__slave___c_a_n.html',1,'']]],
  ['can_5fsynchronisation_5fjump_5fwidth',['CAN_synchronisation_jump_width',['../group___c_a_n__synchronisation__jump__width.html',1,'']]],
  ['can_5ftime_5fquantum_5fin_5fbit_5fsegment_5f1',['CAN_time_quantum_in_bit_segment_1',['../group___c_a_n__time__quantum__in__bit__segment__1.html',1,'']]],
  ['can_5ftime_5fquantum_5fin_5fbit_5fsegment_5f2',['CAN_time_quantum_in_bit_segment_2',['../group___c_a_n__time__quantum__in__bit__segment__2.html',1,'']]],
  ['can_5ftransmit_5fconstants',['CAN_transmit_constants',['../group___c_a_n__transmit__constants.html',1,'']]],
  ['can_5ftx',['CAN_Tx',['../group___c_a_n___tx.html',1,'']]],
  ['can_5fwake_5fup_5fconstants',['CAN_wake_up_constants',['../group___c_a_n__wake__up__constants.html',1,'']]],
  ['cec',['CEC',['../group___c_e_c.html',1,'']]],
  ['cec_5fbitperiod_5fmode',['CEC_BitPeriod_Mode',['../group___c_e_c___bit_period___mode.html',1,'']]],
  ['cec_5fbittiming_5fmode',['CEC_BitTiming_Mode',['../group___c_e_c___bit_timing___mode.html',1,'']]],
  ['cec_5fexported_5fconstants',['CEC_Exported_Constants',['../group___c_e_c___exported___constants.html',1,'']]],
  ['cec_5fexported_5ffunctions',['CEC_Exported_Functions',['../group___c_e_c___exported___functions.html',1,'']]],
  ['cec_5fexported_5fmacros',['CEC_Exported_Macros',['../group___c_e_c___exported___macros.html',1,'']]],
  ['cec_5fflags_5fdefinition',['CEC_flags_definition',['../group___c_e_c__flags__definition.html',1,'']]],
  ['cec_5finterrupts_5fdefinition',['CEC_interrupts_definition',['../group___c_e_c__interrupts__definition.html',1,'']]],
  ['cec_5fown_5faddres',['CEC_Own_Addres',['../group___c_e_c___own___addres.html',1,'']]],
  ['cec_5fprescaler',['CEC_Prescaler',['../group___c_e_c___prescaler.html',1,'']]],
  ['cec_5fprivate_5fdefines',['CEC_Private_Defines',['../group___c_e_c___private___defines.html',1,'']]],
  ['cec_5fprivate_5ffunctionprototypes',['CEC_Private_FunctionPrototypes',['../group___c_e_c___private___function_prototypes.html',1,'']]],
  ['cec_5fprivate_5ffunctions',['CEC_Private_Functions',['../group___c_e_c___private___functions.html',1,'']]],
  ['cec_5fprivate_5fmacros',['CEC_Private_Macros',['../group___c_e_c___private___macros.html',1,'']]],
  ['cec_5fprivate_5ftypesdefinitions',['CEC_Private_TypesDefinitions',['../group___c_e_c___private___types_definitions.html',1,'']]],
  ['cec_5fprivate_5fvariables',['CEC_Private_Variables',['../group___c_e_c___private___variables.html',1,'']]],
  ['complex_20fft_20tables',['Complex FFT Tables',['../group___c_f_f_t___c_i_f_f_t.html',1,'']]],
  ['clock_5fsource_5fto_5foutput_5fon_5fmco_5fpin',['Clock_source_to_output_on_MCO_pin',['../group___clock__source__to__output__on___m_c_o__pin.html',1,'']]],
  ['complex_20conjugate',['Complex Conjugate',['../group__cmplx__conj.html',1,'']]],
  ['complex_20dot_20product',['Complex Dot Product',['../group__cmplx__dot__prod.html',1,'']]],
  ['complex_20magnitude',['Complex Magnitude',['../group__cmplx__mag.html',1,'']]],
  ['complex_20magnitude_20squared',['Complex Magnitude Squared',['../group__cmplx__mag__squared.html',1,'']]],
  ['complex_2dby_2dcomplex_20multiplication',['Complex-by-Complex Multiplication',['../group___cmplx_by_cmplx_mult.html',1,'']]],
  ['complex_2dby_2dreal_20multiplication',['Complex-by-Real Multiplication',['../group___cmplx_by_real_mult.html',1,'']]],
  ['cmsis',['CMSIS',['../group___c_m_s_i_s.html',1,'']]],
  ['cm3_20core_20definitions',['CM3 Core Definitions',['../group___c_m_s_i_s___c_m3__core__definitions.html',1,'']]],
  ['cmsis_20cm3_20core_20function_20interface',['CMSIS CM3 Core Function Interface',['../group___c_m_s_i_s___c_m3___core___function_interface.html',1,'']]],
  ['cmsis_20cm3_20core_20lint_20configuration',['CMSIS CM3 Core Lint Configuration',['../group___c_m_s_i_s___c_m3__core___lint_cinfiguration.html',1,'']]],
  ['cmsis_20cm3_20core_20register',['CMSIS CM3 Core Register',['../group___c_m_s_i_s___c_m3__core__register.html',1,'']]],
  ['cmsis_20cm3_20core_20debug',['CMSIS CM3 Core Debug',['../group___c_m_s_i_s___c_m3___core_debug.html',1,'']]],
  ['cmsis_20cm3_20core_20debug_20interface',['CMSIS CM3 Core Debug Interface',['../group___c_m_s_i_s___c_m3___core_debug_interface.html',1,'']]],
  ['cmsis_20cm3_20interrupt_20type',['CMSIS CM3 Interrupt Type',['../group___c_m_s_i_s___c_m3___interrupt_type.html',1,'']]],
  ['cmsis_20cm3_20itm',['CMSIS CM3 ITM',['../group___c_m_s_i_s___c_m3___i_t_m.html',1,'']]],
  ['cmsis_20cm3_20mpu',['CMSIS CM3 MPU',['../group___c_m_s_i_s___c_m3___m_p_u.html',1,'']]],
  ['cmsis_20cm3_20nvic',['CMSIS CM3 NVIC',['../group___c_m_s_i_s___c_m3___n_v_i_c.html',1,'']]],
  ['cmsis_20cm3_20scb',['CMSIS CM3 SCB',['../group___c_m_s_i_s___c_m3___s_c_b.html',1,'']]],
  ['cmsis_20cm3_20systick',['CMSIS CM3 SysTick',['../group___c_m_s_i_s___c_m3___sys_tick.html',1,'']]],
  ['core_20definitions',['Core Definitions',['../group___c_m_s_i_s__core__base.html',1,'']]],
  ['cmsis_20core_20instruction_20interface',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['cmsis_20core_20register_20access_20functions',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['core_20debug_20registers_20_28coredebug_29',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['cmsis_20global_20defines',['CMSIS Global Defines',['../group___c_m_s_i_s__glob__defs.html',1,'']]],
  ['comp',['COMP',['../group___c_o_m_p.html',1,'']]],
  ['comp_5fblankingsrce',['COMP_BlankingSrce',['../group___c_o_m_p___blanking_srce.html',1,'']]],
  ['comp_5fexported_5fconstants',['COMP_Exported_Constants',['../group___c_o_m_p___exported___constants.html',1,'']]],
  ['comp_20configuration_20locking_20function',['COMP configuration locking function',['../group___c_o_m_p___group3.html',1,'']]],
  ['comp_5fhysteresis',['COMP_Hysteresis',['../group___c_o_m_p___hysteresis.html',1,'']]],
  ['comp_5finvertinginput',['COMP_InvertingInput',['../group___c_o_m_p___inverting_input.html',1,'']]],
  ['comp_5fmode',['COMP_Mode',['../group___c_o_m_p___mode.html',1,'']]],
  ['comp_5fnoninvertinginput',['COMP_NonInvertingInput',['../group___c_o_m_p___non_inverting_input.html',1,'']]],
  ['comp_5foutput',['COMP_Output',['../group___c_o_m_p___output.html',1,'']]],
  ['comp_5foutputlevel',['COMP_OutputLevel',['../group___c_o_m_p___output_level.html',1,'']]],
  ['comp_5foutputpoloarity',['COMP_OutputPoloarity',['../group___c_o_m_p___output_poloarity.html',1,'']]],
  ['comp_5fprivate_5ffunctions',['COMP_Private_Functions',['../group___c_o_m_p___private___functions.html',1,'']]],
  ['comp_5fselection',['COMP_Selection',['../group___c_o_m_p___selection.html',1,'']]],
  ['comp_5fwindowmode',['COMP_WindowMode',['../group___c_o_m_p___window_mode.html',1,'']]],
  ['com_20port_20to_20usb_20vcp_20bridge_20module',['Com Port to USB VCP Bridge Module',['../group___com_usb_bridge_module.html',1,'']]],
  ['configuration_5fpull_2dup_5fpull_2ddown_5fenumeration',['Configuration_Pull-Up_Pull-Down_enumeration',['../group___configuration___pull-_up___pull-_down__enumeration.html',1,'']]],
  ['constants',['Constants',['../group___constants.html',1,'']]],
  ['control_20module',['Control Module',['../group___control.html',1,'']]],
  ['control_20module',['Control Module',['../group___control_module.html',1,'']]],
  ['convolution',['Convolution',['../group___conv.html',1,'']]],
  ['coptercontrol_20bootloader',['CopterControl BootLoader',['../group___copter_control_b_l.html',1,'']]],
  ['correlation',['Correlation',['../group___corr.html',1,'']]],
  ['cosine',['Cosine',['../group__cos.html',1,'']]],
  ['crc',['CRC',['../group___c_r_c.html',1,'']]],
  ['configuration_20of_20the_20crc_20computation_20unit_20functions',['Configuration of the CRC computation unit functions',['../group___c_r_c___group1.html',1,'']]],
  ['crc_20computation_20of_20one_2fmany_2032_2dbit_20data_20functions',['CRC computation of one/many 32-bit data functions',['../group___c_r_c___group2.html',1,'']]],
  ['crc_20independent_20register_20_28idr_29_20access_20functions',['CRC Independent Register (IDR) access functions',['../group___c_r_c___group3.html',1,'']]],
  ['crc_5fprivate_5fdefines',['CRC_Private_Defines',['../group___c_r_c___private___defines.html',1,'']]],
  ['crc_5fprivate_5ffunctionprototypes',['CRC_Private_FunctionPrototypes',['../group___c_r_c___private___function_prototypes.html',1,'']]],
  ['crc_5fprivate_5ffunctions',['CRC_Private_Functions',['../group___c_r_c___private___functions.html',1,'']]],
  ['crc_5fprivate_5fmacros',['CRC_Private_Macros',['../group___c_r_c___private___macros.html',1,'']]],
  ['crc_5fprivate_5ftypesdefinitions',['CRC_Private_TypesDefinitions',['../group___c_r_c___private___types_definitions.html',1,'']]],
  ['crc_5fprivate_5fvariables',['CRC_Private_Variables',['../group___c_r_c___private___variables.html',1,'']]],
  ['crdelay',['crDELAY',['../group__cr_d_e_l_a_y.html',1,'']]],
  ['crqueue_5freceive',['crQUEUE_RECEIVE',['../group__cr_q_u_e_u_e___r_e_c_e_i_v_e.html',1,'']]],
  ['crqueue_5freceive_5ffrom_5fisr',['crQUEUE_RECEIVE_FROM_ISR',['../group__cr_q_u_e_u_e___r_e_c_e_i_v_e___f_r_o_m___i_s_r.html',1,'']]],
  ['crqueue_5fsend',['crQUEUE_SEND',['../group__cr_q_u_e_u_e___s_e_n_d.html',1,'']]],
  ['crqueue_5fsend_5ffrom_5fisr',['crQUEUE_SEND_FROM_ISR',['../group__cr_q_u_e_u_e___s_e_n_d___f_r_o_m___i_s_r.html',1,'']]],
  ['crstart',['crSTART',['../group__cr_s_t_a_r_t.html',1,'']]],
  ['cryp',['CRYP',['../group___c_r_y_p.html',1,'']]],
  ['cryp_5falgorithm_5fdirection',['CRYP_Algorithm_Direction',['../group___c_r_y_p___algorithm___direction.html',1,'']]],
  ['cryp_5falgorithm_5fmode',['CRYP_Algorithm_Mode',['../group___c_r_y_p___algorithm___mode.html',1,'']]],
  ['cryp_5fdata_5ftype',['CRYP_Data_Type',['../group___c_r_y_p___data___type.html',1,'']]],
  ['cryp_5fdma_5ftransfer_5frequests',['CRYP_DMA_transfer_requests',['../group___c_r_y_p___d_m_a__transfer__requests.html',1,'']]],
  ['cryp_5fencryption_5fdecryption_5fmodes_5fdefinition',['CRYP_Encryption_Decryption_modes_definition',['../group___c_r_y_p___encryption___decryption__modes__definition.html',1,'']]],
  ['cryp_5fexported_5fconstants',['CRYP_Exported_Constants',['../group___c_r_y_p___exported___constants.html',1,'']]],
  ['cryp_5fflags_5fdefinition',['CRYP_flags_definition',['../group___c_r_y_p__flags__definition.html',1,'']]],
  ['cryp_20data_20processing_20functions',['CRYP Data processing functions',['../group___c_r_y_p___group2.html',1,'']]],
  ['context_20swapping_20functions',['Context swapping functions',['../group___c_r_y_p___group3.html',1,'']]],
  ['cryp_27s_20dma_20interface_20configuration_20function',['CRYP&apos;s DMA interface Configuration function',['../group___c_r_y_p___group4.html',1,'']]],
  ['cryp_5finterrupts_5fdefinition',['CRYP_interrupts_definition',['../group___c_r_y_p__interrupts__definition.html',1,'']]],
  ['cryp_5fkey_5fsize_5ffor_5faes_5fonly',['CRYP_Key_Size_for_AES_only',['../group___c_r_y_p___key___size__for___a_e_s__only.html',1,'']]],
  ['cryp_5fprivate_5ffunctions',['CRYP_Private_Functions',['../group___c_r_y_p___private___functions.html',1,'']]],
  ['convert_2032_2dbit_20floating_20point_20value',['Convert 32-bit floating point value',['../group__float__to__x.html',1,'']]],
  ['complex_20math_20functions',['Complex Math Functions',['../group__group_cmplx_math.html',1,'']]],
  ['controller_20functions',['Controller Functions',['../group__group_controller.html',1,'']]],
  ['context_20swapping_20functions',['Context swapping functions',['../group___h_a_s_h___group3.html',1,'']]],
  ['communications_20handling_20functions',['Communications handling functions',['../group___i2_c___group2.html',1,'']]],
  ['com_20layer_20functions',['COM layer functions',['../group___p_i_o_s___c_o_m.html',1,'']]],
  ['crc_20functions',['CRC Functions',['../group___p_i_o_s___c_r_c.html',1,'']]],
  ['code_20for_20controlling_20i2c_20based_20escs',['Code for controlling I2C based ESCs',['../group___p_i_o_s___i2_c___e_s_c.html',1,'']]],
  ['code_20for_20osd_20video_20generator',['Code for OSD video generator',['../group___p_i_o_s___v_i_d_e_o.html',1,'']]],
  ['code_20for_20wave_20audio_20generator',['Code for wave audio generator',['../group___p_i_o_s___w_a_v_p_l_a_y.html',1,'']]],
  ['convert_2016_2dbit_20integer_20value',['Convert 16-bit Integer value',['../group__q15__to__x.html',1,'']]],
  ['convert_2032_2dbit_20integer_20value',['Convert 32-bit Integer value',['../group__q31__to__x.html',1,'']]],
  ['convert_208_2dbit_20integer_20value',['Convert 8-bit Integer value',['../group__q7__to__x.html',1,'']]],
  ['com_20port_20to_20radio_20bridge_20module',['Com Port to Radio Bridge Module',['../group___radio_com_bridge_module.html',1,'']]],
  ['command_20path_20state_20machine_20_28cpsm_29_20management_20functions',['Command path state machine (CPSM) management functions',['../group___s_d_i_o___group2.html',1,'']]],
  ['ce_2data_20mode_20management_20functions',['CE-ATA mode management functions',['../group___s_d_i_o___group5.html',1,'']]],
  ['clocks_20management_20functions',['Clocks management functions',['../group___t_i_m___group6.html',1,'']]]
];
