var searchData=
[
  ['vector_20absolute_20value',['Vector Absolute Value',['../group___basic_abs.html',1,'']]],
  ['vector_20addition',['Vector Addition',['../group___basic_add.html',1,'']]],
  ['vector_20multiplication',['Vector Multiplication',['../group___basic_mult.html',1,'']]],
  ['vector_20subtraction',['Vector Subtraction',['../group___basic_sub.html',1,'']]],
  ['vector_20clarke_20transform',['Vector Clarke Transform',['../group__clarke.html',1,'']]],
  ['vector_20copy',['Vector Copy',['../group__copy.html',1,'']]],
  ['vector_20dot_20product',['Vector Dot Product',['../group__dot__prod.html',1,'']]],
  ['vector_20fill',['Vector Fill',['../group___fill.html',1,'']]],
  ['vector_20inverse_20clarke_20transform',['Vector Inverse Clarke Transform',['../group__inv__clarke.html',1,'']]],
  ['vector_20inverse_20park_20transform',['Vector Inverse Park transform',['../group__inv__park.html',1,'']]],
  ['vector_20negate',['Vector Negate',['../group__negate.html',1,'']]],
  ['vector_20offset',['Vector Offset',['../group__offset.html',1,'']]],
  ['vector_20park_20transform',['Vector Park Transform',['../group__park.html',1,'']]],
  ['vector_20scale',['Vector Scale',['../group__scale.html',1,'']]],
  ['vector_20shift',['Vector Shift',['../group__shift.html',1,'']]],
  ['variance',['Variance',['../group__variance.html',1,'']]],
  ['vcoroutineschedule',['vCoRoutineSchedule',['../group__v_co_routine_schedule.html',1,'']]],
  ['vector_5ftable_5fbase',['Vector_Table_Base',['../group___vector___table___base.html',1,'']]],
  ['visualization',['Visualization',['../group___visualization.html',1,'']]],
  ['vsemaphorecreatebinary',['vSemaphoreCreateBinary',['../group__v_semaphore_create_binary.html',1,'']]],
  ['vsemaphorecreatemutex',['vSemaphoreCreateMutex',['../group__v_semaphore_create_mutex.html',1,'']]],
  ['vtaskdelay',['vTaskDelay',['../group__v_task_delay.html',1,'']]],
  ['vtaskdelayuntil',['vTaskDelayUntil',['../group__v_task_delay_until.html',1,'']]],
  ['vtaskdelete',['vTaskDelete',['../group__v_task_delete.html',1,'']]],
  ['vtaskendscheduler',['vTaskEndScheduler',['../group__v_task_end_scheduler.html',1,'']]],
  ['vtaskpriorityset',['vTaskPrioritySet',['../group__v_task_priority_set.html',1,'']]],
  ['vtaskresume',['vTaskResume',['../group__v_task_resume.html',1,'']]],
  ['vtaskresumefromisr',['vTaskResumeFromISR',['../group__v_task_resume_from_i_s_r.html',1,'']]],
  ['vtaskstartscheduler',['vTaskStartScheduler',['../group__v_task_start_scheduler.html',1,'']]],
  ['vtasksuspend',['vTaskSuspend',['../group__v_task_suspend.html',1,'']]],
  ['vtasksuspendall',['vTaskSuspendAll',['../group__v_task_suspend_all.html',1,'']]]
];
