var dir_512e9f2a6b1c2f84e3bf2bb199f80610 =
[
    [ "Constants.h", "_constants_8h.html", "_constants_8h" ],
    [ "DisableMSVCWarnings.h", "_disable_m_s_v_c_warnings_8h.html", null ],
    [ "EnableMSVCWarnings.h", "_enable_m_s_v_c_warnings_8h.html", null ],
    [ "ForwardDeclarations.h", "_forward_declarations_8h.html", "_forward_declarations_8h" ],
    [ "Macros.h", "_macros_8h.html", null ],
    [ "Memory.h", "_memory_8h.html", "_memory_8h" ],
    [ "Meta.h", "_meta_8h.html", [
      [ "ei_meta_true", "structei__meta__true.html", "structei__meta__true" ],
      [ "ei_meta_false", "structei__meta__false.html", "structei__meta__false" ],
      [ "ei_meta_if", "structei__meta__if.html", "structei__meta__if" ],
      [ "ei_meta_if< false, Then, Else >", "structei__meta__if_3_01false_00_01_then_00_01_else_01_4.html", "structei__meta__if_3_01false_00_01_then_00_01_else_01_4" ],
      [ "ei_is_same_type", "structei__is__same__type.html", "structei__is__same__type" ],
      [ "ei_is_same_type< T, T >", "structei__is__same__type_3_01_t_00_01_t_01_4.html", "structei__is__same__type_3_01_t_00_01_t_01_4" ],
      [ "ei_unref", "structei__unref.html", "structei__unref" ],
      [ "ei_unref< T & >", "structei__unref_3_01_t_01_6_01_4.html", "structei__unref_3_01_t_01_6_01_4" ],
      [ "ei_unpointer", "structei__unpointer.html", "structei__unpointer" ],
      [ "ei_unpointer< T * >", "structei__unpointer_3_01_t_01_5_01_4.html", "structei__unpointer_3_01_t_01_5_01_4" ],
      [ "ei_unpointer< T *const  >", "structei__unpointer_3_01_t_01_5const_01_01_4.html", "structei__unpointer_3_01_t_01_5const_01_01_4" ],
      [ "ei_unconst", "structei__unconst.html", "structei__unconst" ],
      [ "ei_unconst< const T >", "structei__unconst_3_01const_01_t_01_4.html", "structei__unconst_3_01const_01_t_01_4" ],
      [ "ei_unconst< T const & >", "structei__unconst_3_01_t_01const_01_6_01_4.html", "structei__unconst_3_01_t_01const_01_6_01_4" ],
      [ "ei_unconst< T const * >", "structei__unconst_3_01_t_01const_01_5_01_4.html", "structei__unconst_3_01_t_01const_01_5_01_4" ],
      [ "ei_cleantype", "structei__cleantype.html", "structei__cleantype" ],
      [ "ei_cleantype< const T >", "structei__cleantype_3_01const_01_t_01_4.html", "structei__cleantype_3_01const_01_t_01_4" ],
      [ "ei_cleantype< const T & >", "structei__cleantype_3_01const_01_t_01_6_01_4.html", "structei__cleantype_3_01const_01_t_01_6_01_4" ],
      [ "ei_cleantype< T & >", "structei__cleantype_3_01_t_01_6_01_4.html", "structei__cleantype_3_01_t_01_6_01_4" ],
      [ "ei_cleantype< const T * >", "structei__cleantype_3_01const_01_t_01_5_01_4.html", "structei__cleantype_3_01const_01_t_01_5_01_4" ],
      [ "ei_cleantype< T * >", "structei__cleantype_3_01_t_01_5_01_4.html", "structei__cleantype_3_01_t_01_5_01_4" ],
      [ "ei_result_of", "structei__result__of.html", null ],
      [ "ei_has_none", "structei__has__none.html", "structei__has__none" ],
      [ "ei_has_std_result_type", "structei__has__std__result__type.html", "structei__has__std__result__type" ],
      [ "ei_has_tr1_result", "structei__has__tr1__result.html", "structei__has__tr1__result" ],
      [ "ei_unary_result_of_select", "structei__unary__result__of__select.html", "structei__unary__result__of__select" ],
      [ "ei_unary_result_of_select< Func, ArgType, sizeof(ei_has_std_result_type)>", "structei__unary__result__of__select_3_01_func_00_01_arg_type_00_01sizeof_07ei__has__std__result__type_08_4.html", "structei__unary__result__of__select_3_01_func_00_01_arg_type_00_01sizeof_07ei__has__std__result__type_08_4" ],
      [ "ei_unary_result_of_select< Func, ArgType, sizeof(ei_has_tr1_result)>", "structei__unary__result__of__select_3_01_func_00_01_arg_type_00_01sizeof_07ei__has__tr1__result_08_4.html", "structei__unary__result__of__select_3_01_func_00_01_arg_type_00_01sizeof_07ei__has__tr1__result_08_4" ],
      [ "ei_result_of< Func(ArgType)>", "structei__result__of_3_01_func_07_arg_type_08_4.html", "structei__result__of_3_01_func_07_arg_type_08_4" ],
      [ "ei_binary_result_of_select", "structei__binary__result__of__select.html", "structei__binary__result__of__select" ],
      [ "ei_binary_result_of_select< Func, ArgType0, ArgType1, sizeof(ei_has_std_result_type)>", "structei__binary__result__of__select_3_01_func_00_01_arg_type0_00_01_arg_type1_00_01sizeof_07ei__has__std__result__type_08_4.html", "structei__binary__result__of__select_3_01_func_00_01_arg_type0_00_01_arg_type1_00_01sizeof_07ei__has__std__result__type_08_4" ],
      [ "ei_binary_result_of_select< Func, ArgType0, ArgType1, sizeof(ei_has_tr1_result)>", "structei__binary__result__of__select_3_01_func_00_01_arg_type0_00_01_arg_type1_00_01sizeof_07ei__has__tr1__result_08_4.html", "structei__binary__result__of__select_3_01_func_00_01_arg_type0_00_01_arg_type1_00_01sizeof_07ei__has__tr1__result_08_4" ],
      [ "ei_result_of< Func(ArgType0, ArgType1)>", "structei__result__of_3_01_func_07_arg_type0_00_01_arg_type1_08_4.html", "structei__result__of_3_01_func_07_arg_type0_00_01_arg_type1_08_4" ],
      [ "ei_meta_sqrt", "classei__meta__sqrt.html", "classei__meta__sqrt" ],
      [ "ei_meta_sqrt< Y, InfX, SupX, true >", "classei__meta__sqrt_3_01_y_00_01_inf_x_00_01_sup_x_00_01true_01_4.html", "classei__meta__sqrt_3_01_y_00_01_inf_x_00_01_sup_x_00_01true_01_4" ],
      [ "ei_scalar_product_traits", "structei__scalar__product__traits.html", "structei__scalar__product__traits" ],
      [ "ei_scalar_product_traits< T, T >", "structei__scalar__product__traits_3_01_t_00_01_t_01_4.html", "structei__scalar__product__traits_3_01_t_00_01_t_01_4" ],
      [ "ei_scalar_product_traits< T, std::complex< T > >", "structei__scalar__product__traits_3_01_t_00_01std_1_1complex_3_01_t_01_4_01_4.html", "structei__scalar__product__traits_3_01_t_00_01std_1_1complex_3_01_t_01_4_01_4" ],
      [ "ei_scalar_product_traits< std::complex< T >, T >", "structei__scalar__product__traits_3_01std_1_1complex_3_01_t_01_4_00_01_t_01_4.html", "structei__scalar__product__traits_3_01std_1_1complex_3_01_t_01_4_00_01_t_01_4" ],
      [ "ei_result_of< ei_scalar_product_op< Scalar >(ArgType0, ArgType1)>", "structei__result__of_3_01ei__scalar__product__op_3_01_scalar_01_4_07_arg_type0_00_01_arg_type1_08_4.html", "structei__result__of_3_01ei__scalar__product__op_3_01_scalar_01_4_07_arg_type0_00_01_arg_type1_08_4" ]
    ] ],
    [ "StaticAssert.h", "_static_assert_8h.html", [
      [ "ei_static_assert", "structei__static__assert.html", null ],
      [ "ei_static_assert< true >", "structei__static__assert_3_01true_01_4.html", "structei__static__assert_3_01true_01_4" ]
    ] ],
    [ "XprHelper.h", "_xpr_helper_8h.html", [
      [ "ei_empty_struct", "structei__empty__struct.html", "structei__empty__struct" ],
      [ "ei_no_assignment_operator", "classei__no__assignment__operator.html", "classei__no__assignment__operator" ],
      [ "EIGEN_EMPTY_STRUCT", "struct_e_i_g_e_n___e_m_p_t_y___s_t_r_u_c_t.html", "struct_e_i_g_e_n___e_m_p_t_y___s_t_r_u_c_t" ],
      [ "ei_int_if_dynamic< Dynamic >", "classei__int__if__dynamic_3_01_dynamic_01_4.html", "classei__int__if__dynamic_3_01_dynamic_01_4" ],
      [ "ei_functor_traits", "structei__functor__traits.html", "structei__functor__traits" ],
      [ "ei_packet_traits", "structei__packet__traits.html", "structei__packet__traits" ],
      [ "ei_unpacket_traits", "structei__unpacket__traits.html", "structei__unpacket__traits" ],
      [ "ei_compute_matrix_flags", "classei__compute__matrix__flags.html", "classei__compute__matrix__flags" ],
      [ "ei_size_at_compile_time", "structei__size__at__compile__time.html", "structei__size__at__compile__time" ],
      [ "ei_eval", "classei__eval.html", null ],
      [ "ei_eval< T, IsDense >", "structei__eval_3_01_t_00_01_is_dense_01_4.html", "structei__eval_3_01_t_00_01_is_dense_01_4" ],
      [ "ei_eval< Matrix< _Scalar, _Rows, _Cols, _StorageOrder, _MaxRows, _MaxCols >, IsDense >", "structei__eval_3_01_matrix_3_01___scalar_00_01___rows_00_01___cols_00_01___storage_order_00_01__1037d2a498088b119b5d3833e22bfc54.html", "structei__eval_3_01_matrix_3_01___scalar_00_01___rows_00_01___cols_00_01___storage_order_00_01__1037d2a498088b119b5d3833e22bfc54" ],
      [ "ei_plain_matrix_type", "structei__plain__matrix__type.html", "structei__plain__matrix__type" ],
      [ "ei_plain_matrix_type_column_major", "structei__plain__matrix__type__column__major.html", "structei__plain__matrix__type__column__major" ],
      [ "ei_plain_matrix_type_row_major", "structei__plain__matrix__type__row__major.html", "structei__plain__matrix__type__row__major" ],
      [ "ei_must_nest_by_value", "structei__must__nest__by__value.html", "structei__must__nest__by__value" ],
      [ "ei_must_nest_by_value< NestByValue< T > >", "structei__must__nest__by__value_3_01_nest_by_value_3_01_t_01_4_01_4.html", "structei__must__nest__by__value_3_01_nest_by_value_3_01_t_01_4_01_4" ],
      [ "ei_nested", "structei__nested.html", "structei__nested" ],
      [ "ei_are_flags_consistent", "structei__are__flags__consistent.html", "structei__are__flags__consistent" ],
      [ "BlockReturnType", "struct_block_return_type.html", "struct_block_return_type" ],
      [ "ei_cast_return_type", "structei__cast__return__type.html", "structei__cast__return__type" ]
    ] ]
];