var globals_type =
[
    [ "a", "globals_type.html", null ],
    [ "b", "globals_type_0x62.html", null ],
    [ "c", "globals_type_0x63.html", null ],
    [ "d", "globals_type_0x64.html", null ],
    [ "e", "globals_type_0x65.html", null ],
    [ "f", "globals_type_0x66.html", null ],
    [ "g", "globals_type_0x67.html", null ],
    [ "h", "globals_type_0x68.html", null ],
    [ "i", "globals_type_0x69.html", null ],
    [ "l", "globals_type_0x6c.html", null ],
    [ "m", "globals_type_0x6d.html", null ],
    [ "n", "globals_type_0x6e.html", null ],
    [ "o", "globals_type_0x6f.html", null ],
    [ "p", "globals_type_0x70.html", null ],
    [ "q", "globals_type_0x71.html", null ],
    [ "r", "globals_type_0x72.html", null ],
    [ "s", "globals_type_0x73.html", null ],
    [ "t", "globals_type_0x74.html", null ],
    [ "u", "globals_type_0x75.html", null ],
    [ "v", "globals_type_0x76.html", null ],
    [ "w", "globals_type_0x77.html", null ],
    [ "x", "globals_type_0x78.html", null ],
    [ "y", "globals_type_0x79.html", null ],
    [ "z", "globals_type_0x7a.html", null ]
];