var group___g_c_s_plugins =
[
    [ "Importexportplugin", "group__importexportplugin.html", "group__importexportplugin" ],
    [ "QML Viewer Plugin", "group___o_p_map_plugin.html", "group___o_p_map_plugin" ],
    [ "Antenna Track Gadget Plugin", "group___antenna_track_gadget_plugin.html", "group___antenna_track_gadget_plugin" ],
    [ "OpenPilot boards support Plugin", "group___boards___open_pilot_plugin.html", "group___boards___open_pilot_plugin" ],
    [ "Quantec boards support Plugin", "group___boards___quantec.html", "group___boards___quantec" ],
    [ "STM boards support Plugin", "group___boards___stm.html", "group___boards___stm" ],
    [ "Tau Labs boards support Plugin", "group___boards___tau_labs_plugin.html", "group___boards___tau_labs_plugin" ],
    [ "Config Plugin", "group___config_plugin.html", "group___config_plugin" ],
    [ "Plugin", "group___congig.html", null ],
    [ "Core Plugin", "group___core_plugin.html", "group___core_plugin" ],
    [ "plugin", "group___config.html", "group___config" ],
    [ "Console Plugin", "group___console_plugin.html", "group___console_plugin" ],
    [ "Debug Gadget Plugin", "group___debug_gadget_plugin.html", "group___debug_gadget_plugin" ],
    [ "Dial Plugin", "group___dial_plugin.html", "group___dial_plugin" ],
    [ "Do Nothing Plugin", "group___do_nothing_plugin.html", "group___do_nothing_plugin" ],
    [ "Empty Gadget Plugin", "group___empty_gadget_plugin.html", "group___empty_gadget_plugin" ],
    [ "GCSControl Gadget Plugin", "group___g_c_s_control_gadget_plugin.html", "group___g_c_s_control_gadget_plugin" ],
    [ "GPS Gadget Plugin", "group___g_p_s_gadget_plugin.html", "group___g_p_s_gadget_plugin" ],
    [ "HITLv2 Plugin", "group___h_i_t_l_plugin.html", "group___h_i_t_l_plugin" ],
    [ "IP Telemetry Plugin", "group___i_p_conn_plugin.html", "group___i_p_conn_plugin" ],
    [ "Linear Dial Plugin", "group___linear_dial_plugin.html", "group___linear_dial_plugin" ],
    [ "Logging", "group___logging.html", "group___logging" ],
    [ "Loggingplugin", "group__loggingplugin.html", "group__loggingplugin" ],
    [ "ModelView Plugin", "group___model_view_plugin.html", "group___model_view_plugin" ],
    [ "Motion Capture Plugin", "group___mo_cap_plugin.html", "group___mo_cap_plugin" ],
    [ "Planner Pluggin", "group___path.html", "group___path" ],
    [ "Map Plugin", "group___path_planner.html", "group___path_planner" ],
    [ "PowerLog", "group___power_log.html", "group___power_log" ],
    [ "Powerlogplugin", "group__powerlogplugin.html", "group__powerlogplugin" ],
    [ "Raw HID Plugin", "group___raw_h_i_d_plugin.html", "group___raw_h_i_d_plugin" ],
    [ "Scope Gadget Plugin", "group___scope_plugin.html", "group___scope_plugin" ],
    [ "UAVObjects Plugin", "group___u_a_v_objects_plugin.html", "group___u_a_v_objects_plugin" ],
    [ "Serial Connection Plugin", "group___serial_plugin.html", "group___serial_plugin" ],
    [ "Wizard  Plugin", "group___setup.html", "group___setup" ],
    [ "SetupWizardPlugin", "group___setup_wizard_plugin.html", "group___setup_wizard_plugin" ],
    [ "Alarms Messaging Plugin", "group___system.html", "group___system" ],
    [ "System Health Plugin", "group___system_health_plugin.html", "group___system_health_plugin" ],
    [ "UAVObject Browser Plugin", "group___u_a_v_object_browser_plugin.html", "group___u_a_v_object_browser_plugin" ],
    [ "UAVObjectUtil Plugin", "group___u_a_v_object_util_plugin.html", "group___u_a_v_object_util_plugin" ],
    [ "UAVSettings Import/Export Plugin", "group___u_a_v_settings_import_export.html", "group___u_a_v_settings_import_export" ],
    [ "UAVTalk Plugin", "group___u_a_v_talk_plugin.html", "group___u_a_v_talk_plugin" ],
    [ "relay plugin", "group___u_a_v_talk.html", "group___u_a_v_talk" ],
    [ "Serial and USB Uploader Plugin", "group___uploader.html", "group___uploader" ],
    [ "YModem Serial Uploader Plugin", "group___y_modem_uploader.html", "group___y_modem_uploader" ],
    [ "Welcome Plugin", "group___welcome_plugin.html", "group___welcome_plugin" ]
];