var group___g_c_s_plugins =
[
    [ "Importexportplugin", "group__importexportplugin.html", null ],
    [ "QML Viewer Plugin", "group___o_p_map_plugin.html", null ],
    [ "Antenna Track Gadget Plugin", "group___antenna_track_gadget_plugin.html", null ],
    [ "OpenPilot boards support Plugin", "group___boards___open_pilot_plugin.html", null ],
    [ "Quantec boards support Plugin", "group___boards___quantec.html", null ],
    [ "STM boards support Plugin", "group___boards___stm.html", null ],
    [ "Tau Labs boards support Plugin", "group___boards___tau_labs_plugin.html", null ],
    [ "Config Plugin", "group___config_plugin.html", null ],
    [ "Plugin", "group___congig.html", null ],
    [ "Core Plugin", "group___core_plugin.html", null ],
    [ "Console Plugin", "group___console_plugin.html", null ],
    [ "Debug Gadget Plugin", "group___debug_gadget_plugin.html", null ],
    [ "Dial Plugin", "group___dial_plugin.html", null ],
    [ "Do Nothing Plugin", "group___do_nothing_plugin.html", null ],
    [ "Empty Gadget Plugin", "group___empty_gadget_plugin.html", null ],
    [ "GCSControl Gadget Plugin", "group___g_c_s_control_gadget_plugin.html", null ],
    [ "GPS Gadget Plugin", "group___g_p_s_gadget_plugin.html", null ],
    [ "HITL Plugin", "group___h_i_t_l_plugin.html", null ],
    [ "IP Telemetry Plugin", "group___i_p_conn_plugin.html", null ],
    [ "Linear Dial Plugin", "group___linear_dial_plugin.html", null ],
    [ "Logging", "group___logging.html", null ],
    [ "Loggingplugin", "group__loggingplugin.html", null ],
    [ "ModelView Plugin", "group___model_view_plugin.html", null ],
    [ "Motion Capture Plugin", "group___mo_cap_plugin.html", null ],
    [ "Notification plugin", "group___notify_plugin.html", null ],
    [ "OSG Earth View plugin to visualize UAV in 3D", "group___o_s_g_earth_view_pluging.html", null ],
    [ "Planner Pluggin", "group___path.html", null ],
    [ "Path Planner Gadget Plugin", "group___path_planner_gadget_plugin.html", null ],
    [ "Map Plugin", "group___path_planner.html", null ],
    [ "Primary Flight Display Plugin", "group___p_f_d_plugin.html", null ],
    [ "PowerLog", "group___power_log.html", null ],
    [ "Powerlogplugin", "group__powerlogplugin.html", null ],
    [ "Raw HID Plugin", "group___raw_h_i_d_plugin.html", null ],
    [ "Scope Gadget Plugin", "group___scope_plugin.html", null ],
    [ "UAVObjects Plugin", "group___u_a_v_objects_plugin.html", null ],
    [ "Serial Connection Plugin", "group___serial_plugin.html", null ],
    [ "Wizard  Plugin", "group___setup.html", null ],
    [ "SetupWizardPlugin", "group___setup_wizard_plugin.html", null ],
    [ "Alarms Messaging Plugin", "group___system.html", null ],
    [ "System Health Plugin", "group___system_health_plugin.html", null ],
    [ "TelemetryScheduler Plugin", "group___telemetry_scheduler_plugin.html", null ],
    [ "Telemetry Scheduler Plugin", "group___telemetry_scheduler.html", null ],
    [ "UAVObject Browser Plugin", "group___u_a_v_object_browser_plugin.html", null ],
    [ "UAVObjectUtil Plugin", "group___u_a_v_object_util_plugin.html", null ],
    [ "UAVSettings Import/Export Plugin", "group___u_a_v_settings_import_export.html", null ],
    [ "UAVTalk Plugin", "group___u_a_v_talk_plugin.html", null ],
    [ "relay plugin", "group___u_a_v_talk.html", null ],
    [ "Serial and USB Uploader Plugin", "group___uploader.html", null ],
    [ "YModem Serial Uploader Plugin", "group___y_modem_uploader.html", null ],
    [ "Waypoint Editor Gadget Plugin", "group___waypoint_editor_gadget_plugin.html", null ],
    [ "Welcome Plugin", "group___welcome_plugin.html", null ]
];