var modules =
[
    [ "OPMapWidget", "group___o_p_map_widget.html", null ],
    [ "Circular Byte-Buffer Structure and Function Library (buffer.c)", "group__buffer.html", null ],
    [ "GCS Plugins", "group___g_c_s_plugins.html", "group___g_c_s_plugins" ],
    [ "Third-party integration", "group__rd_party.html", "group__rd_party" ],
    [ "ConnectionDiagram", "group___connection_diagram.html", null ],
    [ "LevellingUtil", "group___levelling_util.html", null ],
    [ "OutputCalibrationUtil", "group___output_calibration_util.html", null ],
    [ "AbstractWizardPage", "group___abstract_wizard_page.html", null ],
    [ "AutoUpdatePage", "group___auto_update_page.html", null ],
    [ "ControllerPage", "group___controller_page.html", null ],
    [ "FixedWingPage", "group___fixed_wing_page.html", null ],
    [ "HeliPage", "group___heli_page.html", null ],
    [ "InputPage", "group___input_page.html", null ],
    [ "LevellingPage", "group___levelling_page.html", null ],
    [ "MultiPage", "group___multi_page.html", null ],
    [ "NotYetImplementedPage", "group___not_yet_implemented_page.html", null ],
    [ "OutputCalibrationPage", "group___output_calibration_page.html", null ],
    [ "OutputPage", "group___output_page.html", null ],
    [ "RebootPage", "group___reboot_page.html", null ],
    [ "SavePage", "group___save_page.html", null ],
    [ "SummaryPage", "group___summary_page.html", null ],
    [ "SurfacePage", "group___surface_page.html", null ],
    [ "VehiclePage", "group___vehicle_page.html", null ],
    [ "VehicleConfigurationHelper", "group___vehicle_configuration_helper.html", null ],
    [ "VehicleConfigurationSource", "group___vehicle_configuration_source.html", null ],
    [ "Scheduler GCS Plugins", "group___telemetry.html", "group___telemetry" ],
    [ "Plugin", "group___u_a_v_object_widget_utils.html", null ]
];