var namespaces =
[
    [ "Aggregation", "namespace_aggregation.html", "namespace_aggregation" ],
    [ "Core", "namespace_core.html", "namespace_core" ],
    [ "core", "namespacecore.html", "namespacecore" ],
    [ "Core::Constants", "namespace_core_1_1_constants.html", "namespace_core_1_1_constants" ],
    [ "Core::Internal", "namespace_core_1_1_internal.html", "namespace_core_1_1_internal" ],
    [ "Core::Internal::Ui", "namespace_core_1_1_internal_1_1_ui.html", null ],
    [ "device", "namespacedevice.html", null ],
    [ "ExtensionSystem", "namespace_extension_system.html", "namespace_extension_system" ],
    [ "ExtensionSystem::Internal", "namespace_extension_system_1_1_internal.html", "namespace_extension_system_1_1_internal" ],
    [ "ExtensionSystem::Internal::Ui", "namespace_extension_system_1_1_internal_1_1_ui.html", null ],
    [ "internals", "namespaceinternals.html", "namespaceinternals" ],
    [ "mapcontrol", "namespacemapcontrol.html", "namespacemapcontrol" ],
    [ "MyPlugin", "namespace_my_plugin.html", "namespace_my_plugin" ],
    [ "OP_DFU", "namespace_o_p___d_f_u.html", "namespace_o_p___d_f_u" ],
    [ "org", "namespaceorg.html", null ],
    [ "org::taulabs", "namespaceorg_1_1taulabs.html", null ],
    [ "org.taulabs.uavtalk", "namespaceorg_1_1taulabs_1_1uavtalk.html", "namespaceorg_1_1taulabs_1_1uavtalk" ],
    [ "Plugin1", "namespace_plugin1.html", "namespace_plugin1" ],
    [ "Plugin2", "namespace_plugin2.html", "namespace_plugin2" ],
    [ "Plugin3", "namespace_plugin3.html", "namespace_plugin3" ],
    [ "projections", "namespaceprojections.html", "namespaceprojections" ],
    [ "QtConcurrent", "namespace_qt_concurrent.html", "namespace_qt_concurrent" ],
    [ "uavobject", "namespaceuavobject.html", "namespaceuavobject" ],
    [ "uavobjecttemplate", "namespaceuavobjecttemplate.html", "namespaceuavobjecttemplate" ],
    [ "Ui", "namespace_ui.html", null ],
    [ "uploader", "namespaceuploader.html", "namespaceuploader" ],
    [ "Utils", "namespace_utils.html", "namespace_utils" ],
    [ "Welcome", "namespace_welcome.html", "namespace_welcome" ],
    [ "Welcome::Internal", "namespace_welcome_1_1_internal.html", "namespace_welcome_1_1_internal" ]
];