var namespaces =
[
    [ "Aggregation", "namespace_aggregation.html", null ],
    [ "BerkeleyDB", "namespace_berkeley_d_b.html", null ],
    [ "Core", "namespace_core.html", "namespace_core" ],
    [ "core", "namespacecore.html", null ],
    [ "device", "namespacedevice.html", null ],
    [ "Eigen", "namespace_eigen.html", null ],
    [ "ExtensionSystem", "namespace_extension_system.html", "namespace_extension_system" ],
    [ "glc", "namespaceglc.html", null ],
    [ "glcXmlUtil", "namespaceglc_xml_util.html", null ],
    [ "internals", "namespaceinternals.html", null ],
    [ "mapcontrol", "namespacemapcontrol.html", null ],
    [ "MyPlugin", "namespace_my_plugin.html", null ],
    [ "OP_DFU", "namespace_o_p___d_f_u.html", null ],
    [ "org", "namespaceorg.html", "namespaceorg" ],
    [ "Plugin1", "namespace_plugin1.html", null ],
    [ "Plugin2", "namespace_plugin2.html", null ],
    [ "Plugin3", "namespace_plugin3.html", null ],
    [ "projections", "namespaceprojections.html", null ],
    [ "QtConcurrent", "namespace_qt_concurrent.html", null ],
    [ "Qwt", "namespace_qwt.html", null ],
    [ "QwtClip", "namespace_qwt_clip.html", null ],
    [ "QwtTriangle", "namespace_qwt_triangle.html", null ],
    [ "QxtMetaObject", "namespace_qxt_meta_object.html", null ],
    [ "QxtType", "namespace_qxt_type.html", null ],
    [ "QxtXmlRpc", "namespace_qxt_xml_rpc.html", null ],
    [ "SharedTools", "namespace_shared_tools.html", null ],
    [ "uavobject", "namespaceuavobject.html", null ],
    [ "uavobjecttemplate", "namespaceuavobjecttemplate.html", null ],
    [ "Ui", "namespace_ui.html", null ],
    [ "uploader", "namespaceuploader.html", null ],
    [ "Utils", "namespace_utils.html", null ],
    [ "Welcome", "namespace_welcome.html", "namespace_welcome" ]
];